# Generated by Django 6.1 on 2026-09-07 14:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('service_orders', '0010_ordemservico_service_ord_status_706532_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=200, unique=True)),
                ('unidade', models.CharField(blank=True, max_length=10)),
                ('saldo', models.DecimalField(decimal_places=3, default=0, max_digits=12)),
                ('estoque_minimo', models.DecimalField(decimal_places=3, default=0, max_digits=12)),
                ('custo_unitario', models.DecimalField(decimal_places=2, default=0, help_text='Custo médio ponderado, atualizado a cada entrada.', max_digits=12)),
                ('ativo', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'material',
                'verbose_name_plural': 'materiais',
                'ordering': ['descricao'],
            },
        ),
        migrations.CreateModel(
            name='MovimentoEstoque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('ENTRADA', 'Entrada'), ('SAIDA', 'Saída'), ('AJUSTE', 'Ajuste de inventário')], max_length=10)),
                ('quantidade', models.DecimalField(decimal_places=3, help_text='Sempre positiva. Em AJUSTE, é o saldo que foi contado.', max_digits=12)),
                ('saldo_apos', models.DecimalField(decimal_places=3, max_digits=12)),
                ('custo_unitario', models.DecimalField(decimal_places=2, default=0, help_text='Preenchido na ENTRADA (custo da compra).', max_digits=12)),
                ('documento', models.CharField(blank=True, help_text='Nota fiscal / fornecedor / referência.', max_length=120)),
                ('observacao', models.TextField(blank=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movimentos', to='inventory.material')),
                ('ordem_servico', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimentos_estoque', to='service_orders.ordemservico')),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimentos_estoque', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'movimento de estoque',
                'verbose_name_plural': 'movimentos de estoque',
                'ordering': ['-criado_em', '-id'],
                'indexes': [models.Index(fields=['material', '-criado_em'], name='inventory_m_materia_032e11_idx'), models.Index(fields=['ordem_servico'], name='inventory_m_ordem_s_e6d380_idx')],
            },
        ),
    ]
