# Generated by Django 6.1 on 2026-08-31 19:20

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Etapa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('tipo_ponto', models.CharField(blank=True, choices=[('REDE', 'Ponto de rede'), ('AR', 'Ponto de ar'), ('ENERGIA', 'Ponto de energia'), ('TELEFONE', 'Ponto de telefone'), ('LPRS', 'Ponto de LPRS'), ('REDE_ESTABILIZADA', 'Rede estabilizada elétrica'), ('ELETRICA_220', 'Elétrica 220V'), ('OUTRO', 'Outro')], max_length=20)),
                ('localizacao', models.CharField(blank=True, max_length=200)),
                ('meta', models.PositiveIntegerField(default=1, verbose_name='Quantidade prevista')),
                ('realizado', models.PositiveIntegerField(default=0, verbose_name='Quantidade instalada')),
                ('ordem', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['ordem', 'id'],
            },
        ),
        migrations.CreateModel(
            name='FotoEtapa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagem', models.ImageField(upload_to='obras/etapas/%Y/%m/')),
                ('legenda', models.CharField(blank=True, max_length=200)),
                ('enviado_em', models.DateTimeField(auto_now_add=True)),
                ('enviado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('etapa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fotos', to='projects.etapa')),
            ],
            options={
                'ordering': ['-enviado_em'],
            },
        ),
        migrations.CreateModel(
            name='HistoricoEtapa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateTimeField(auto_now_add=True)),
                ('quantidade_anterior', models.PositiveIntegerField()),
                ('quantidade_nova', models.PositiveIntegerField()),
                ('observacao', models.CharField(blank=True, max_length=300)),
                ('etapa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historico', to='projects.etapa')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-data'],
            },
        ),
        migrations.CreateModel(
            name='Projeto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(editable=False, max_length=20, unique=True)),
                ('nome', models.CharField(max_length=200)),
                ('descricao', models.TextField(blank=True, verbose_name='Escopo')),
                ('responsavel', models.CharField(blank=True, max_length=150)),
                ('tipo', models.CharField(choices=[('INSTALACAO_PROJETO', 'Instalação de projeto'), ('MUDANCA_LAYOUT', 'Mudança de layout'), ('MANUTENCAO', 'Manutenção'), ('OUTRO', 'Outro')], default='INSTALACAO_PROJETO', max_length=20)),
                ('status', models.CharField(choices=[('PLANEJADO', 'Planejado'), ('EM_ANDAMENTO', 'Em andamento'), ('CONCLUIDO', 'Concluído'), ('CANCELADO', 'Cancelado')], default='PLANEJADO', max_length=15)),
                ('areas_afetadas', models.JSONField(blank=True, default=list)),
                ('data_mudanca', models.DateField(blank=True, null=True)),
                ('data_termino_previsto', models.DateField(blank=True, null=True)),
                ('data_conclusao', models.DateField(blank=True, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('criado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projetos_criados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'projeto (obra)',
                'verbose_name_plural': 'projetos (obras)',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='PlantaProjeto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arquivo', models.FileField(upload_to='obras/plantas/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(['pdf', 'png', 'jpg', 'jpeg', 'webp'])])),
                ('pagina', models.PositiveIntegerField(blank=True, null=True)),
                ('descricao', models.CharField(blank=True, max_length=200)),
                ('enviado_em', models.DateTimeField(auto_now_add=True)),
                ('projeto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plantas', to='projects.projeto')),
            ],
            options={
                'ordering': ['pagina', 'id'],
            },
        ),
        migrations.AddField(
            model_name='etapa',
            name='projeto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='etapas', to='projects.projeto'),
        ),
        migrations.CreateModel(
            name='AssinaturaProjeto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('papel', models.CharField(choices=[('CIENTE', 'Ciente da alteração'), ('SUPERVISOR', 'Supervisor de processos')], max_length=15)),
                ('nome', models.CharField(max_length=150)),
                ('assinatura', models.ImageField(upload_to='obras/assinaturas/%Y/%m/')),
                ('assinado_em', models.DateTimeField(auto_now_add=True)),
                ('projeto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assinaturas', to='projects.projeto')),
            ],
            options={
                'ordering': ['assinado_em'],
            },
        ),
    ]
