# Generated by Django 6.1 on 2026-08-27 00:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notificacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('OS_ATRIBUIDA', 'Ordem de serviço atribuída'), ('SOLICITACAO_APROVADA', 'Solicitação aprovada'), ('SOLICITACAO_REJEITADA', 'Solicitação rejeitada'), ('NOVA_SOLICITACAO', 'Nova solicitação para revisar')], max_length=30)),
                ('mensagem', models.CharField(max_length=255)),
                ('link', models.CharField(blank=True, help_text='Rota do app pra abrir ao tocar na notificação.', max_length=200)),
                ('lida', models.BooleanField(default=False)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('destinatario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notificacoes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-criado_em'],
            },
        ),
    ]
