# Generated by Django 6.1 on 2026-09-01 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificacao',
            name='tipo',
            field=models.CharField(choices=[('OS_ATRIBUIDA', 'Ordem de serviço atribuída'), ('OS_CONCLUIDA', 'Ordem de serviço concluída'), ('SOLICITACAO_APROVADA', 'Solicitação aprovada'), ('SOLICITACAO_REJEITADA', 'Solicitação rejeitada'), ('NOVA_SOLICITACAO', 'Nova solicitação para revisar')], max_length=30),
        ),
    ]
