# Generated by Django 6.1 on 2026-08-27 16:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_orders', '0002_ordemservico_latitude_abertura_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordemservico',
            name='status',
            field=models.CharField(choices=[('ABERTA', 'Aberta'), ('ATRIBUIDA', 'Atribuída'), ('EM_ANDAMENTO', 'Em andamento'), ('PAUSADA', 'Pausada'), ('CONCLUIDA', 'Concluída'), ('CANCELADA', 'Cancelada')], default='ABERTA', max_length=15),
        ),
        migrations.CreateModel(
            name='PausaOrdemServico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motivo', models.CharField(choices=[('ALMOCO', 'Almoço'), ('FALTA_MATERIAL', 'Falta de material'), ('AGUARDANDO_CLIENTE', 'Aguardando cliente'), ('OUTRO', 'Outro')], max_length=20)),
                ('observacao', models.TextField(blank=True)),
                ('iniciada_em', models.DateTimeField(auto_now_add=True)),
                ('retomada_em', models.DateTimeField(blank=True, null=True)),
                ('ordem_servico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pausas', to='service_orders.ordemservico')),
            ],
            options={
                'ordering': ['-iniciada_em'],
            },
        ),
    ]
