# Generated by Django 6.1 on 2026-08-27 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_orders', '0003_alter_ordemservico_status_pausaordemservico'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordemservico',
            name='relato',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
