# Generated by Django 6.1 on 2026-08-27 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_orders', '0004_ordemservico_relato'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaterialCatalogo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=200, unique=True)),
                ('unidade_padrao', models.CharField(blank=True, max_length=10)),
                ('usos', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'material do catálogo',
                'verbose_name_plural': 'catálogo de materiais',
                'ordering': ['-usos', 'descricao'],
            },
        ),
        migrations.CreateModel(
            name='ServicoCatalogo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=300, unique=True)),
                ('usos', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'serviço do catálogo',
                'verbose_name_plural': 'catálogo de serviços',
                'ordering': ['-usos', 'descricao'],
            },
        ),
    ]
