# Generated by Django 6.1 on 2026-09-06 18:16

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
        ('service_orders', '0009_limpa_catalogo_materiais'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='ordemservico',
            index=models.Index(fields=['status'], name='service_ord_status_706532_idx'),
        ),
        migrations.AddIndex(
            model_name='ordemservico',
            index=models.Index(fields=['status', 'data_conclusao'], name='service_ord_status_8b0f06_idx'),
        ),
    ]
