# Generated by Django 6.1 on 2026-08-26 15:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistroPonto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('ENTRADA', 'Entrada'), ('SAIDA_INTERVALO', 'Saída para intervalo'), ('VOLTA_INTERVALO', 'Volta do intervalo'), ('SAIDA', 'Saída')], max_length=20)),
                ('registrado_em', models.DateTimeField()),
                ('sincronizado_em', models.DateTimeField(auto_now_add=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='ponto/%Y/%m/')),
                ('origem_offline', models.BooleanField(default=False, help_text='Marcado quando o registro foi feito sem conexão e sincronizado depois.')),
                ('funcionario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registros_ponto', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-registrado_em'],
            },
        ),
    ]
