# Generated by Django 6.1 on 2026-08-26 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timeclock', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='registroponto',
            name='endereco',
            field=models.CharField(blank=True, help_text='Endereço aproximado (geocodificação reversa).', max_length=255),
        ),
        migrations.AddField(
            model_name='registroponto',
            name='justificativa',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='registroponto',
            name='precisao_metros',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Precisão (raio, em metros) informada pelo GPS do dispositivo no momento do registro.', max_digits=8, null=True),
        ),
    ]
