# Generated by Django 6.1 on 2026-08-27 00:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timeclock', '0002_registroponto_endereco_registroponto_justificativa_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SolicitacaoPonto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('AJUSTE', 'Ajuste de ponto'), ('JUSTIFICATIVA_AUSENCIA', 'Justificativa de ausência')], max_length=25)),
                ('data_referencia', models.DateField(help_text='Dia a que a solicitação se refere.')),
                ('tipo_ponto_solicitado', models.CharField(blank=True, choices=[('ENTRADA', 'Entrada'), ('SAIDA_INTERVALO', 'Saída para intervalo'), ('VOLTA_INTERVALO', 'Volta do intervalo'), ('SAIDA', 'Saída')], max_length=20)),
                ('horario_solicitado', models.TimeField(blank=True, null=True)),
                ('descricao', models.TextField(help_text='Motivo/justificativa do funcionário.')),
                ('status', models.CharField(choices=[('PENDENTE', 'Pendente'), ('APROVADA', 'Aprovada'), ('REJEITADA', 'Rejeitada')], default='PENDENTE', max_length=10)),
                ('analisado_em', models.DateTimeField(blank=True, null=True)),
                ('resposta_gestor', models.TextField(blank=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('analisado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='solicitacoes_analisadas', to=settings.AUTH_USER_MODEL)),
                ('funcionario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitacoes_ponto', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-criado_em'],
            },
        ),
    ]
