# Generated by Django 6.1 on 2026-08-28 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timeclock', '0003_solicitacaoponto'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitacaoponto',
            name='pontos_anteriores',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='solicitacaoponto',
            name='pontos_propostos',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='solicitacaoponto',
            name='tipo',
            field=models.CharField(choices=[('AJUSTE', 'Ajuste de ponto'), ('AJUSTE_DIA', 'Ajuste do dia inteiro'), ('JUSTIFICATIVA_AUSENCIA', 'Justificativa de ausência')], max_length=25),
        ),
    ]
