# Generated by Django 6.1 on 2026-09-06 18:07

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timeclock', '0004_solicitacaoponto_pontos_anteriores_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='registroponto',
            index=models.Index(fields=['funcionario', 'registrado_em'], name='timeclock_r_funcion_aec4a0_idx'),
        ),
        migrations.AddConstraint(
            model_name='registroponto',
            constraint=models.UniqueConstraint(fields=('funcionario', 'tipo', 'registrado_em'), name='ponto_sem_duplicata_exata'),
        ),
    ]
