# Generated by Django 6.1 on 2026-08-26 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='carga_horaria_diaria_minutos',
            field=models.PositiveIntegerField(default=528, help_text='Carga horária esperada por dia útil (segunda a sexta), em minutos. Padrão: 8h48 (528min).'),
        ),
    ]
