# Generated by Django 6.1 on 2026-08-26 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_usuario_carga_horaria_diaria_minutos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='carga_horaria_diaria_minutos',
        ),
        migrations.AddField(
            model_name='usuario',
            name='periodo1_fim',
            field=models.TimeField(blank=True, default='12:00', null=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='periodo1_inicio',
            field=models.TimeField(blank=True, default='08:00', null=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='periodo2_fim',
            field=models.TimeField(blank=True, default='18:00', null=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='periodo2_inicio',
            field=models.TimeField(blank=True, default='13:00', null=True),
        ),
    ]
