# Generated by Django 6.1 on 2026-08-26 16:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_usuario_carga_horaria_diaria_minutos_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='periodo1_fim',
            field=models.TimeField(blank=True, default=datetime.time(12, 0), null=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='periodo1_inicio',
            field=models.TimeField(blank=True, default=datetime.time(8, 0), null=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='periodo2_fim',
            field=models.TimeField(blank=True, default=datetime.time(18, 0), null=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='periodo2_inicio',
            field=models.TimeField(blank=True, default=datetime.time(13, 0), null=True),
        ),
    ]
