# Generated by Django 6.1 on 2026-08-31 20:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_usuario_periodo1_fim_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='encarregado_responsavel',
            field=models.ForeignKey(blank=True, limit_choices_to={'papel': 'ENCARREGADO'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='equipe', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='papel',
            field=models.CharField(choices=[('TECNICO', 'Técnico'), ('ENCARREGADO', 'Encarregado'), ('GESTOR', 'Gestor'), ('RH', 'RH'), ('ADMIN', 'Administrador')], default='TECNICO', max_length=20),
        ),
    ]
