# Generated by Django 6.1 on 2026-09-02 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_usuario_encarregado_responsavel_alter_usuario_papel'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='agencia',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AddField(
            model_name='usuario',
            name='bairro',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='usuario',
            name='banco',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AddField(
            model_name='usuario',
            name='cep',
            field=models.CharField(blank=True, max_length=9),
        ),
        migrations.AddField(
            model_name='usuario',
            name='cidade',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='usuario',
            name='complemento',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AddField(
            model_name='usuario',
            name='conta',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='usuario',
            name='contato_emergencia_nome',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='usuario',
            name='contato_emergencia_parentesco',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='usuario',
            name='contato_emergencia_telefone',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='usuario',
            name='cpf',
            field=models.CharField(blank=True, max_length=14),
        ),
        migrations.AddField(
            model_name='usuario',
            name='ctps_numero',
            field=models.CharField(blank=True, max_length=20, verbose_name='CTPS nº'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='ctps_serie',
            field=models.CharField(blank=True, max_length=20, verbose_name='CTPS série'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='data_admissao',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='data_desligamento',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='data_nascimento',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='estado',
            field=models.CharField(blank=True, max_length=2, verbose_name='UF'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='estado_civil',
            field=models.CharField(blank=True, choices=[('SOLTEIRO', 'Solteiro(a)'), ('CASADO', 'Casado(a)'), ('DIVORCIADO', 'Divorciado(a)'), ('VIUVO', 'Viúvo(a)'), ('UNIAO_ESTAVEL', 'União estável')], max_length=20),
        ),
        migrations.AddField(
            model_name='usuario',
            name='genero',
            field=models.CharField(blank=True, choices=[('MASCULINO', 'Masculino'), ('FEMININO', 'Feminino'), ('OUTRO', 'Outro'), ('NAO_INFORMAR', 'Prefiro não informar')], max_length=20),
        ),
        migrations.AddField(
            model_name='usuario',
            name='logradouro',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='usuario',
            name='nome_mae',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='usuario',
            name='numero_endereco',
            field=models.CharField(blank=True, max_length=10, verbose_name='número'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='pis',
            field=models.CharField(blank=True, max_length=20, verbose_name='PIS/NIS'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='pix',
            field=models.CharField(blank=True, max_length=140),
        ),
        migrations.AddField(
            model_name='usuario',
            name='rg',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='usuario',
            name='salario',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
