# Generated by Django 6.1 on 2026-09-03 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_usuario_agencia_usuario_bairro_usuario_banco_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='registra_ponto',
            field=models.BooleanField(default=True, help_text='Desmarque para quem não bate ponto (sócios, diretoria).', verbose_name='registra ponto'),
        ),
    ]
